const collaborators = [
  {
    id: '1',
    first: 'Michael',
    last: 'Scott',
    position: 'Principal Investigator',
    tasks: [],
  },
  {
    id: '2',
    first: 'Dwight',
    last: 'Schrute',
    position: 'Postdoctoral Researcher',
    tasks: [],
  },
  {
    id: '3',
    first: 'Jim',
    last: 'Halpert',
    position: 'Postdoctoral Researcher',
    tasks: [],
  },
  {
    id: '4',
    first: 'Pam',
    last: 'Beesly',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '5',
    first: 'Oscar',
    last: 'Martinez',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '6',
    first: 'Kelly',
    last: 'Kapoor',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '7',
    first: 'Stanley',
    last: 'Hudson',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '8',
    first: 'Kevin',
    last: 'Malone',
    position: 'Undergraduate Student',
    tasks: [],
  },
  {
    id: '9',
    first: 'Angela',
    last: 'Martin',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '10',
    first: 'Phyllis',
    last: 'Vance',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '11',
    first: 'Creed',
    last: 'Bratton',
    position: 'Undergraduate Student',
    tasks: [],
  },
  {
    id: '12',
    first: 'Darryl',
    last: 'Philbin',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '13',
    first: 'Toby',
    last: 'Flenderson',
    position: 'Laboratory Technician',
    tasks: [],
  },
  {
    id: '14',
    first: 'Erin',
    last: 'Hannon',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '15',
    first: 'Andy',
    last: 'Bernard',
    position: 'PhD Student',
    tasks: [],
  },
  {
    id: '16',
    first: 'Ryan',
    last: 'Howard',
    position: 'Undergraduate Student',
    tasks: [],
  },
  {
    id: '17',
    first: 'Meredith',
    last: 'Palmer',
    position: 'Undergraduate Student',
    tasks: [],
  },
];

export default collaborators;
